#!/system/bin/sh

# enable interactiveX governor by default

insmod /system/lib/modules/symsearch.ko
insmod /system/lib/modules/cpufreq_interactive.ko
insmod /system/lib/modules/cpufreq_conservative.ko
busybox echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
busybox echo conservative > /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
busybox echo interactive > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor